// Launch triage rows 73-80 (platform stage): static regression checks.
// 73 OBS-11  prebuilt Tailwind stylesheet instead of the in-browser compiler
// 74 OBS-10  each app-shell file precached once, by the URL the page uses
// 75 OBS-12  no build-stamp messages in the console on load
// 78 OFFLINE-QUEUE-001  (client half) a later refusal keeps earlier reasons
// 80 X5      the till names a catalog price that replaced the cart's price
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
let failures = 0;
const check = (name, ok, detail = '') => { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail ? ' — ' + detail : ''}`); if (!ok) failures++; };

const index = read('frontend/index.html');
const app = read('frontend/js/app.js');
const offline = read('frontend/js/offline.js');
const css = fs.existsSync(path.join(root, 'frontend/css/tailwind.css')) ? read('frontend/css/tailwind.css') : '';

// --- 73 ---------------------------------------------------------------------
check('73: index.html no longer loads the Tailwind in-browser compiler', !/tailwindcss[-\d.]*\.js|cdn\.tailwindcss|tailwind\.config\s*=/.test(index));
check('73: the vendored compiler file is gone', !fs.existsSync(path.join(root, 'frontend/assets/vendor/tailwindcss-3.4.17.js')));
const sheets = [...index.matchAll(/<link rel="stylesheet" href="([^"]+)">/g)].map(m => m[1]);
check('73: prebuilt stylesheet is linked last (where the compiler injected its styles)', sheets[sheets.length - 1] === '/css/tailwind.css', sheets.join(', '));
check('73: stylesheet is the generated file', css.startsWith('/* Generated by scripts/build-tailwind-css.js (tailwindcss@3.4.17)'));
const has = sel => css.includes(sel + '{') || css.includes(sel + ',');
for (const sel of ['.hidden', '.flex', '.bg-cardBg', '.text-textMain', '.text-primary', '.border-borderCol', '.bg-primary\\/10', '.max-h-\\[90vh\\]', '.sm\\:grid-cols-2', '.md\\:flex', '.hover\\:bg-primaryHover:hover', '.font-mono'])
  check(`73: stylesheet has ${sel}`, has(sel));
check('73: Cauldra theme colours compiled', /\.bg-bgMain\{[^}]*rgb\(7 11 20/.test(css) && /\.text-danger\{[^}]*rgb\(217 65 65/.test(css));
check('73: Naira mono stack compiled', /\.font-mono\{font-family:[^}]*Cauldra Currency/.test(css));
const config = require(path.join(root, 'scripts/tailwind/tailwind.config.js'));
check('73: build config keeps class-based dark mode and the twelve theme colours', config.darkMode === 'class' && Object.keys(config.theme.extend.colors).length === 12);
check('73: native bundle verifier requires the stylesheet', /'css\/tailwind\.css'/.test(read('scripts/verify-native-bundle.js')));
const rowBase = app.match(/const rowBase = "([^"]+)";/);
check('73: expense custom-category row carries one text colour', !!rowBase && !/\btext-(textMain|primary|textSec)\b/.test(rowBase[1]) && /class="\$\{rowBase\} border-t border-borderCol mt-1 pt-2 text-primary font-semibold"/.test(app));

// --- 74 ---------------------------------------------------------------------
const sw = read('frontend/sw.js');
const ctx = { self: { addEventListener() {}, location: { origin: 'https://example.test' } }, caches: {}, fetch() {}, URL, Promise, console };
const lists = vm.runInNewContext(sw + '\n;({ SHELL_CACHE, SHELL_ASSETS, SHELL_DOCUMENTS })', ctx);
const fileFor = url => url === '/' ? 'frontend/index.html' : url.startsWith('/frontend/') ? url.slice(1) : 'frontend' + url;
const files = lists.SHELL_ASSETS.map(fileFor);
const dupes = files.filter((f, i) => files.indexOf(f) !== i);
check('74: no file is precached under two URLs', dupes.length === 0, dupes.join(', '));
check('74: no precache URL outside the page\'s own paths', !lists.SHELL_ASSETS.some(u => u.startsWith('/frontend/')));
const missing = files.filter(f => !fs.existsSync(path.join(root, f)));
check('74: every precached file exists', missing.length === 0, missing.join(', '));
const pageLocal = [...index.matchAll(/<(?:link rel="stylesheet"|script) (?:href|src)="(\/[^"]+)"/g)].map(m => m[1]);
const uncached = pageLocal.filter(u => !lists.SHELL_ASSETS.includes(u) && !/libphonenumber/.test(u));
check('74: every shell stylesheet/script the page loads is precached', uncached.length === 0, uncached.join(', '));
check('74: the app\'s own stylesheet is network-first (a shell document)', lists.SHELL_DOCUMENTS.includes('/css/tailwind.css'));
check('74: cache version bumped so old caches are dropped', lists.SHELL_CACHE !== 'cauldra-shell-v12-launch-i18n-polish');

// --- 75 ---------------------------------------------------------------------
check('75: no build-stamp console messages', !/console\.(log|info)\([^)]*app\.js build/.test(app));

// --- 78 (client) --------------------------------------------------------------
const quarantine = offline.slice(offline.indexOf('async function quarantineActive'), offline.indexOf('async function quarantineActive') + 900);
check('78: quarantine skips changes already refused for their own reason', /if \(row\.status === "conflict"\) continue;/.test(quarantine));

// --- 80 -----------------------------------------------------------------------
const checkout = app.slice(app.indexOf('async function completePOSCheckout'), app.indexOf('// --- POS multi-warehouse selection modal'));
check('80: sale message shown after the sale dialog closes', checkout.indexOf('closeSaleModal();') > -1 && checkout.indexOf('closeSaleModal();') < checkout.indexOf('showToast(saleDone, "success")'));
check('80: price adjustments are named in a warning', /price_adjustments/.test(checkout) && /sales\.catalogPriceApplied/.test(checkout) && /"warning"\)/.test(checkout));
const applied = [...app.matchAll(/catalogPriceApplied: "([^"]+)", catalogPriceLine: "([^"]+)"/g)];
check('80: warning text in all five launch languages', applied.length === 5);
check('80: every translation keeps its placeholders', applied.every(m => m[1].includes('{items}') && ['{name}', '{charged}', '{submitted}'].every(p => m[2].includes(p))));

console.log(failures ? `${failures} FAILED` : 'ALL PASS');
process.exit(failures ? 1 : 0);
