// OPS-ACCURACY-001: static checks of the Private Ops console.
// Column set, responsive priorities, honest empty states, stale health, and
// the console's own prebuilt stylesheet (the in-browser Tailwind compiler it
// used to load was removed with row 73, leaving Ops unstyled).
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
let failures = 0;
const check = (name, ok, detail = '') => { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${!ok && detail ? ' — ' + detail : ''}`); if (!ok) failures++; };

const index = read('platform/index.html');
const html = read('platform/console.html');
const js = read('platform/js/console.js');
const css = fs.existsSync(path.join(root, 'platform/ops.css')) ? read('platform/ops.css') : '';
const main = read('backend/main.py');

// --- stylesheet (row 73 regression) ----------------------------------------
check('Ops no longer loads the removed Tailwind compiler', !/tailwindcss[-\d.]*\.js|tailwind\.config\s*=/.test(index));
check('Ops links its prebuilt stylesheet', /<link rel="stylesheet" href="ops\.css">/.test(index));
check('Ops keeps the icon font', /fontawesome\/css\/all\.min\.css/.test(index));
check('ops.css is served from the Ops path', /PLATFORM_PANEL_PATH \+ "\/ops\.css"/.test(main));
check('ops.css is generated', css.startsWith('/* Generated by scripts/build-tailwind-css.js (tailwindcss@3.4.17)'));
const has = sel => css.includes(sel + '{') || css.includes(sel + ',');
for (const sel of ['.bg-sidebarBg', '.w-\\[220px\\]', '.md\\:sticky', '.-translate-x-full', '.lg\\:grid-cols-4', '.hidden', '.lg\\:table-cell', '.md\\:table-cell', '.sm\\:table-cell', '.bg-danger\\/15', '.text-textSec', '.grid-cols-2'])
    check(`ops.css has ${sel}`, has(sel));

// --- Overview: eight cards, two panels ---------------------------------------
const overview = html.slice(html.indexOf('data-view="overview"'), html.indexOf('data-view="businesses"'));
const labels = [...overview.matchAll(/<div class="stat-label">([^<]+)<\/div>/g)].map(m => m[1].trim());
check('Overview has exactly the eight agreed cards',
    JSON.stringify(labels.slice(0, 8)) === JSON.stringify(['Total Businesses', 'Active Businesses', 'Trialing', 'Paying Businesses', 'Revenue This Month', 'Trial Conversion', 'AI Spend This Month', 'Needs Attention']), labels.join(', '));
check('Overview keeps two panels: Business Growth and Recent Attention', /Business Growth/.test(overview) && /Recent Attention/.test(overview) && (overview.match(/stat-label/g) || []).length === 10);

// --- Businesses table ---------------------------------------------------------
const thead = (html.match(/<table class="data-table" id="businesses-table">\s*<thead><tr>([\s\S]*?)<\/tr><\/thead>/) || [])[1] || '';
const cols = [...thead.matchAll(/<th[^>]*>([^<]+)<\/th>/g)].map(m => m[1]);
check('Businesses columns', JSON.stringify(cols) === JSON.stringify(['Business', 'Joined', 'Plan', 'Status', 'Health', 'Users', 'Last Active', 'Billing', 'Paid to Cauldra']), cols.join(', '));
check('AI Credits / AI Cost / Lifetime Rev. left the Businesses table', !/AI Credits<\/th>|AI Cost<\/th>|Lifetime Rev/.test(thead));
const compactHidden = [...thead.matchAll(/<th class="hidden [a-z]+:table-cell"[^>]*>([^<]+)<\/th>/g)].map(m => m[1]);
check('Compact layout keeps Business, Plan (+Status), Users, Last Active, Billing', JSON.stringify(compactHidden) === JSON.stringify(['Joined', 'Status', 'Health', 'Paid to Cauldra']), compactHidden.join(', '));
check('Plan cell carries the Status pill on small screens', /\$\{planPill\(b\.plan_label, b\.plan\)\}<div class="md:hidden mt-1">\$\{statusPill/.test(js));
for (const id of ['biz-plan-filter', 'biz-status-filter', 'biz-health-filter', 'biz-activity-filter', 'biz-sort'])
    check(`Businesses has ${id}`, html.includes(`id="${id}"`));
for (const s of ['newest', 'oldest', 'recently_active', 'least_active', 'trial_ending', 'highest_paid'])
    check(`sort option ${s}`, html.includes(`<option value="${s}">`));

// --- behaviour of the pure helpers --------------------------------------------
const pick = name => { const m = js.match(new RegExp(`function ${name}\\([^)]*\\) \\{[\\s\\S]*?\\n\\}`)); return m ? m[0] : ''; };
const ctx = { escapeHtml: s => String(s), fmtDate: iso => `D(${iso})`, fmtDateTime: iso => `DT(${iso})`, Date };
vm.createContext(ctx);
vm.runInContext([pick('daysText'), pick('billingText'), pick('lastActive'), pick('joinedDate'), pick('healthIsStale')].join('\n'), ctx);
check('Trial billing reads "Trial ends … / N days left"', /Trial ends D\(x\)[\s\S]*3 days left/.test(ctx.billingText({ kind: 'trial_ends', date: 'x', days_left: 3 })));
check('Paid billing reads "Renews …"', ctx.billingText({ kind: 'renews', date: 'x' }).startsWith('Renews D(x)'));
check('Cancelled billing reads "Access until …"', ctx.billingText({ kind: 'access_until', date: 'x' }).startsWith('Access until D(x)'));
check('Expired billing reads "Expired …"', ctx.billingText({ kind: 'expired', date: 'x' }) === 'Expired D(x)');
check('No activity reads "Never", not a dash', /Never/.test(ctx.lastActive(null)));
check('Unknown join date reads "Not recorded"', /Not recorded/.test(ctx.joinedDate(null)));
const now = Date.now();
check('A fresh health result is not stale', ctx.healthIsStale({ checked_at: new Date(now - 60e3).toISOString(), fresh_seconds: 300 }) === false);
check('A health result older than the window is stale', ctx.healthIsStale({ checked_at: new Date(now - 301e3).toISOString(), fresh_seconds: 300 }) === true);
check('Stale results render as Stale, not their old colour', /HEALTH_STYLE\[stale \? "stale" : c\.status\]/.test(js));

// --- honesty labels -------------------------------------------------------------
check('Refunds are labelled Unavailable, not ₦0', /Refunds \/ Reversals <span class="prov-tag">Unavailable<\/span>/.test(html));
check('MRR is labelled Calculated', /MRR <span class="prov-tag">Calculated<\/span>/.test(html));
check('Failed Webhooks counter renders Unavailable for null', /v === null \? "Unavailable"/.test(js) && /Failed Webhooks \(24H\)/.test(js));
check('Manual FX override is marked MANUAL', /MANUAL override active/.test(html));
check('Budgets are internal, not customer allowances', /NOT customer AI-credit allowances/.test(html));
check('Custom pricing model is a secondary action', /<summary[^>]*>Add a custom model<\/summary>/.test(html));
check('Business Detail never renders merchant sales/customers/inventory', !/\/sales|\/customers|\/products|\/expenses/.test(js));
check('Every Ops call goes through /api/platform', [...js.matchAll(/api(?:Get|Post|Put)\(`?"?([^`"$?]+)/g)].every(m => m[1].startsWith('/api/platform/')));

if (failures) { console.log(`\n${failures} FAILED`); process.exit(1); }
console.log('\nAll Ops console checks passed');
