"""PRICE-UPGRADE-001 — post-fix pricing matrix.

Recomputes every higher-tier upgrade (6 sources x every higher plan/interval)
at five positions of the source paid period, by calling the backend's own
upgrade_quote_amounts() and add_billing_interval() — no database, no network,
no Paystack. Writes a Markdown table.

    PYTHONPATH=backend python3 scripts/price_upgrade_matrix.py OUT.md
"""
import os
import sys
from datetime import datetime, timedelta

os.environ.setdefault('PYTHON_DOTENV_DISABLED', '1')
os.environ.setdefault('SUPPLY_AI_SKIP_DB_STARTUP_CHECK', 'true')
os.environ.setdefault('DATABASE_URL', 'postgresql+psycopg://matrix:matrix@127.0.0.1:65432/matrix')
os.environ.setdefault('SUPPLY_AI_SECRET_KEY', 'pricing-matrix-only-0123456789012345678901234567890123')
import main  # noqa: E402

PLANS = sorted(main.PLAN_CONFIG, key=lambda p: main.PLAN_RANK[p])
LABEL = {p: main.PLAN_CONFIG[p]['label'] for p in PLANS}
POSITIONS = [('start', 0.0), ('25%', 0.25), ('50%', 0.5), ('75%', 0.75), ('1 min left', None)]
START = datetime(2026, 10, 1)


def naira(kobo):
    return f"₦{kobo / 100:,.2f}"


def iso(dt):
    return dt.strftime('%Y-%m-%d %H:%M')


def rows():
    n = 0
    for fp in PLANS[:-1]:
        for fi in ('monthly', 'annual'):
            end = main.add_billing_interval(START, fi)
            for tp in PLANS[PLANS.index(fp) + 1:]:
                for ti in ('monthly', 'annual'):
                    for label, frac in POSITIONS:
                        now = end - timedelta(minutes=1) if frac is None else START + (end - START) * frac
                        n += 1
                        base = {'n': n, 'from': f"{LABEL[fp]} {fi.title()}", 'to': f"{LABEL[tp]} {ti.title()}", 'pos': label,
                                'days': (end - START).days}
                        try:
                            q = main.upgrade_quote_amounts(fp, fi, tp, ti, START, end, now)
                        except main.UpgradeNotQuotable as r:
                            ok = r.unused_credit_kobo > r.new_price_kobo - main.UPGRADE_MINIMUM_CHARGE_KOBO and fi == 'annual' and ti == 'monthly'
                            yield {**base, 'frac': (end - now) / (end - START), 'credit': r.unused_credit_kobo, 'value': r.new_price_kobo,
                                   'due': None, 'start': None, 'through': None,
                                   'status': 'PASS' if ok else 'FAIL',
                                   'reason': f"refused: unused credit exceeds one {ti} term; {LABEL[tp]} Annual or change at renewal offered"}
                            continue
                        new_end = main.add_billing_interval(now, ti)
                        expected_credit = round(main.plan_amount_naira(fp, fi) * 100 * q['unused_fraction'])
                        checks = [q['unused_credit_kobo'] == expected_credit,
                                  q['new_price_kobo'] == main.plan_amount_naira(tp, ti) * 100,
                                  q['amount_due_kobo'] == q['new_price_kobo'] - q['unused_credit_kobo'],
                                  q['amount_due_kobo'] >= main.UPGRADE_MINIMUM_CHARGE_KOBO,
                                  isinstance(q['amount_due_kobo'], int),
                                  q['new_paid_through_if_paid_now'] == new_end,
                                  0.0 <= q['unused_fraction'] <= 1.0]
                        yield {**base, 'frac': q['unused_fraction'], 'credit': q['unused_credit_kobo'], 'value': q['new_price_kobo'],
                               'due': q['amount_due_kobo'], 'start': now, 'through': new_end,
                               'status': 'PASS' if all(checks) else 'FAIL',
                               'reason': 'one full new term bought for its list price less the unused value' if all(checks) else f'checks {checks}'}


def main_():
    out = sys.argv[1]
    data = list(rows())
    lines = ["# Pricing matrix — PRICE-UPGRADE-001 post-fix", "",
             "Generated by `scripts/price_upgrade_matrix.py` from the backend's own `upgrade_quote_amounts()` and `add_billing_interval()` (no database, no network, no Paystack).",
             "",
             "**Model:** the upgrade payment buys one full term of the destination plan and interval, starting when Paystack confirms it. The unused value of the source paid period is credited at the price actually paid. The paid-through time becomes confirmation + one destination term, and the next renewal (full destination price) is anchored there.",
             "",
             "**Formula:** `fraction = remaining ÷ period seconds` (clamped 0–1) · `credit = round(source kobo × fraction)` · `due = destination term kobo − credit` · refused when `credit > destination term kobo − 100`. Kobo = naira × 100, once. No tax or fee is added by Cauldra.",
             "",
             "**Assumptions:** source period starts 2026-10-01 00:00 UTC (monthly 31 days, annual 365 days); payment is confirmed at the quote time shown, so 'Period start' = the confirmation time.",
             "",
             "| # | From | To | Position | Source period (days) | Remaining fraction | Unused credit | Destination service bought (value) | Charge | Kobo to Paystack | New period start | New paid-through = next renewal | Status | Reason |",
             "|---:|---|---|---|---:|---:|---:|---|---:|---:|---|---|---|---|"]
    for r in data:
        term = 'one year' if r['to'].endswith('Annual') else 'one month'
        lines.append(f"| {r['n']} | {r['from']} | {r['to']} | {r['pos']} | {r['days']} | {r['frac']:.6f} | {naira(r['credit'])} | "
                     f"{term} of {r['to']} ({naira(r['value'])}) | {naira(r['due']) if r['due'] is not None else '— (refused)'} | "
                     f"{r['due'] if r['due'] is not None else '—'} | {iso(r['start']) if r['start'] else '—'} | {iso(r['through']) if r['through'] else '—'} | "
                     f"{r['status']} | {r['reason']} |")
    passed = sum(r['status'] == 'PASS' for r in data)
    refused = sum(r['due'] is None for r in data)
    lines += ["", f"**Rows:** {len(data)} · **PASS:** {passed} · **FAIL:** {len(data) - passed} · of which refused (expected, annual → monthly only): {refused} · SUSPECT: 0.", ""]
    open(out, 'w', encoding='utf-8').write("\n".join(lines))
    print(len(data), passed, refused)
    return 0 if passed == len(data) else 1


if __name__ == '__main__':
    sys.exit(main_())
